In [10]:
word = 'oxygen'
# word = 'the'

In [11]:
print(word[0])
print(word[1])
print(word[4])



o
x
e


In [16]:
word = 'the'
for char in word:
    print(char)

t
h
e


In [20]:
for i in range(5, 10, 2):
    print(i)

5
7
9


In [21]:
5**3 

125

In [23]:
result = 1
exponential = 3
x = 5
for number in range(0, exponential):
    result = result * x
    
print(result)

125


In [25]:
mylist = [1, 3, 5, 7]
print(mylist)

[1, 3, 5, 7]


In [28]:
mylist[-1]

7

In [29]:
for i in mylist:
    print(i)

1
3
5
7


In [30]:
names = ['Maria', 'Alice', 'James']

In [31]:
names

['Maria', 'Alice', 'James']

In [33]:
names[0] = 'Jake'

In [34]:
names

['Jake', 'Alice', 'James']

In [35]:
name = 'Jake'

In [37]:
name = 'Maria'

In [38]:
name

'Maria'

In [46]:
x = [1, 2, 3]


In [47]:
y = list(x)

In [48]:
y

[1, 2, 3]

In [49]:
x[0] = 'Darwin'

In [50]:
x

['Darwin', 2, 3]

In [51]:
y

[1, 2, 3]

In [52]:
x = ['Darwin', 1, 3.0]

In [53]:
x = [['papper', 'onion'],
    ['bread', 'pasta'],
    ['apple']]

In [55]:
x[0][1]

'onion'

In [57]:
x = [['a', 'b'], 1, 2]

y = x
z = list(x)

In [58]:
x[0][0] = 'A'

In [59]:
x

[['A', 'b'], 1, 2]

In [60]:
y


[['A', 'b'], 1, 2]

In [61]:
x[1] = 5

In [62]:
x

[['A', 'b'], 5, 2]

In [63]:
y

[['A', 'b'], 5, 2]

In [64]:
z

[['A', 'b'], 1, 2]

In [65]:
x.append(12)

In [66]:
x

[['A', 'b'], 5, 2, 12]

In [67]:
x.pop(0)

['A', 'b']

In [69]:
x.reverse()

In [70]:
x

[12, 2, 5]

In [71]:
x[0:2]

[12, 2]

In [72]:
x[:2]

[12, 2]

In [73]:
x[1:]

[2, 5]

In [74]:
x = [1, 2, 4, 6, 6]

In [75]:
x[0:4:2]

[1, 4]

In [76]:
x

[1, 2, 4, 6, 6]

In [77]:
y 

[12, 2, 5]

In [78]:
x + y

[1, 2, 4, 6, 6, 12, 2, 5]

In [79]:
x * 2

[1, 2, 4, 6, 6, 1, 2, 4, 6, 6]

In [84]:
string_for_slicing = 'Observation date: 25.2.2021'
list_for_slicing = [['fluorine', 'F'], 
                   ['chlorine', 'Cl'],
                   ['bromine', 'Br'],
                   ['iodine', 'I'], 
                   ['astatine', 'At']]

In [85]:
print(string_for_slicing[-4:])
print(list_for_slicing[-4:])

2021
[['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


In [86]:
num = 37

if num < 100 and num > 0:
    print('number between 0 and 100')
elif num > 100 or num < 0:
    print('the number greater than 100 or less than 0')
else:
    print('the is not greater than 100')
    

the is not greater than 100


In [88]:

import numpy as np

In [90]:
data = np.loadtxt(fname='data/inflammation-01.csv',
                  delimiter=',')

In [91]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [92]:
data.shape

(60, 40)

In [96]:
data[:, 4].shape

(60,)

In [101]:
np.max(data, axis=0).shape

(40,)

In [107]:
max_inflammation_0 = np.max(data, axis=0)[0]
print(max_inflammation_0)
max_inflammation_20 = np.max(data, axis=0)[20]
print(max_inflammation_20)

0.0
20.0


In [ ]:
if np.sum(np.min(data, axis=0)) == 0:
    print('Minima sum to zero')
elif max_inflammation_0 == 0 and max_inflammation_20 == 20:
    print('Check required')
else:
    print('Data look ok')

In [111]:
mylist = []

if not mylist:
    print('mylist is False')

mylist is False


In [112]:
x = 23
x += 1
print(x)
x *= 4
print(x)

24
96


In [113]:
'inflammation-01.csv'.startswith('inflamm')

True

In [115]:
filenames = ['inflammation-01.csv', 'inflammation-02.csv',
            'inflammation-03.csv', 'inflammation-04.csv',
            'small-01.csv', 'small-02.csv', 'src.py']
inflammation_data = []
small_data = []
other_data = []


In [116]:
for myfile in filenames:
    if myfile.startswith('inflamm'):
        inflammation_data.append(myfile)
    elif myfile.startswith('small'):
        small_data.append(myfile)
    else:
        other_data.append(myfile)

In [117]:
inflammation_data

['inflammation-01.csv',
 'inflammation-02.csv',
 'inflammation-03.csv',
 'inflammation-04.csv']

In [118]:
small_data

['small-01.csv', 'small-02.csv']

In [119]:
other_data

['src.py']

In [136]:
def fahr_to_celsius(temp, temp2=0.0):
    """
    Converts the temperature in fahr. to celsius
    
    :param temp: float, a temperature in fahr. 
    
    Example
    ------
    .....
    """
    temp_celsius = ((temp - 32) * (5/9))
    print(temp2)
    return temp_celsius

def celsius_to_kelvin(temp_c):
    temp_k = temp_c + 273.15
    return temp_k

def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k
    

In [135]:
help(fahr_to_celsius)

Help on function fahr_to_celsius in module __main__:

fahr_to_celsius(temp, temp2=0.0)
    Converts the temperature in fahr. to celsius
    
    :param temp: float, a temperature in fahr.



In [138]:
fahr_to_celsius(212, temp2=32)
print(temp)

32


NameError: name 'temp' is not defined

In [124]:
celsius_to_kelvin(0.)

273.15

In [126]:
fahr_to_kelvin(212)

373.15

In [ ]:
def sanity_check(data):
    
    max_inflammation_0 = np.max(data, axis=0)[0]
    max_inflammation_20 = np.max(data, axis=0)[20]
    
    if np.sum(np.min(data, axis=0)) == 0:
        print('Minima sum to zero')
    elif max_inflammation_0 == 0 and max_inflammation_20 == 20:
        print('Check required')
    else:
        print('Data look ok')

In [140]:
data.shape

(60, 40)

In [141]:
def additional_function(data):
    
    return data


def offset_mean(data, target_mean_value):
    
    rescaled_data = (data - np.mean(data)) + target_mean_value
    
    return rescaled_data

data1 = offset_mean(data, 23)
data2 = additional_function(data1)



In [142]:
offset_mean(data, 2.0)

array([[-4.14875, -4.14875, -3.14875, ..., -1.14875, -4.14875, -4.14875],
       [-4.14875, -3.14875, -2.14875, ..., -3.14875, -4.14875, -3.14875],
       [-4.14875, -3.14875, -3.14875, ..., -2.14875, -3.14875, -3.14875],
       ...,
       [-4.14875, -3.14875, -3.14875, ..., -3.14875, -3.14875, -3.14875],
       [-4.14875, -4.14875, -4.14875, ..., -4.14875, -2.14875, -4.14875],
       [-4.14875, -4.14875, -3.14875, ..., -3.14875, -3.14875, -4.14875]])

In [143]:
test_data = np.zeros((3, 3))

In [144]:
test_data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [145]:
offset_mean(test_data, 3)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [148]:
def test_offset_mean(target_value):
    
    test_data = np.zeros((3, 3))
    
    mydata = offset_mean(test_data, target_value)
    
    assert mydata[0, 0] == target_value
    
    

In [149]:
test_offset_mean(4)

In [152]:
patient_max = np.max(data, axis=1)

In [153]:
assert patient_max.shape == (60, )
assert patient_max.dtype == 'float32'

AssertionError: 

In [155]:
def favourite_ice_cream():
    ice_creams = ['vanilla', 'chocolate', 'lemon']
    print(ice_creams[3])
    
favourite_ice_cream()

IndexError: list index out of range

In [160]:
def some_function():
    message = 'hello'
    print(message)
    return message

In [163]:
greetings = 'hello'

In [164]:
gretings

NameError: name 'gretings' is not defined

In [166]:
count = 0 
for number in range(10):
    count = count + number
    
print('Count=', count)

Count= 45


In [167]:
numbers = [1, 2, 3, 4]

numbers[0]

1

In [168]:
numbers[7]

IndexError: list index out of range

In [171]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [178]:
%%writefile myfile.txt
'Hello'

Overwriting myfile.txt


In [182]:
myfile = open('myfile.txt', 'r')
hello = myfile.read()

In [183]:
hello

"'Hello'\n"

In [185]:
mylist = [1, 3, 4]
mylist[0] = 'Darwin'

mylist

['Darwin', 3, 4]

In [190]:
mytuple = (1, 3, 4)

mytuple[-1]
mytuple[1] = 'Darwin'

TypeError: 'tuple' object does not support item assignment

In [203]:
mydict = {'one': 'monday',
         'two': 'tuesday'}

mydict['one']
mydict['two']


KeyError: 0

In [195]:
mydict.items()

dict_items([('one', 'monday'), ('two', 'tuesday')])

In [197]:
def print_message(day):
    messages = {'monday': 'today is monday',
                'tuesday': 'finally tuesday',
                'wednesday': 'today is wednesday',
                'thursday': 'almost at the end'
                }
    print(messages[day])
    
def print_monday_message():
    print_message('monday')
    
print_monday_message()

today is monday


In [ ]:
%%debug
x = 1.2

import math

assert math.isclose(x, 1.234), 'x is not as expected'

NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(2)<module>()

ipdb> x
1.2


In [199]:
?np.isclose

In [ ]:
def is_overlapping(rect1, rect2):
    """
    Checks that two rectangles are overlapping
    
    :param rect1: coordinates of the first rectangle
    :param rect2: coordinates of the second
    
    """
    
    
    
